# Basic {{{1

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# View {{{1

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  " Use solarized as colorscheme.
  autocmd MyAutoCmd VimEnter * nested colorscheme solarized
  " Assume a dark background.
  set background=dark
  " Stop displaying these typefaces.
  let g:solarized_bold = 0
  let g:solarized_italic = 0
  let g:solarized_underline = 0
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vim-fugitive', 'vimfiler.vim', 'vimshell.vim', 'unite.vim', 'gundo']
hook_add = '''
  let g:lightline = {
      \ 'colorscheme' : 'solarized',
      \ 'mode_map'    : { 'c' : 'NORMAL' },
      \ 'active'      : {
      \   'left'      : [ [ 'mode', 'paste' ], [ 'fugitive', 'filename' ] ],
      \ },
      \ 'component_function' : {
      \   'modified'     : 'LightLineModified',
      \   'readonly'     : 'LightLineReadonly',
      \   'fugitive'     : 'LightLineFugitive',
      \   'filename'     : 'LightLineFilename',
      \   'fileformat'   : 'LightLineFileformat',
      \   'filetype'     : 'LightLineFiletype',
      \   'fileencoding' : 'LightLineFileencoding',
      \   'mode'         : 'LightLineMode',
      \ },
      \ 'separator'    : { 'left' : "\ue0b0", 'right' : "\ue0b2" },
      \ 'subseparator' : { 'left' : "\ue0b1", 'right' : "\ue0b3" },
      \ }

  function! LightLineModified()
    return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
  endfunction

  function! LightLineReadonly()
    return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? "\ue0a2" : ''
  endfunction

  function! LightLineFilename()
    return ('' != LightLineReadonly() ? LightLineReadonly() . ' ' : '') .
         \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
         \  &ft == 'unite' ? unite#get_status_string() :
         \  &ft == 'vimshell' ? vimshell#get_status_string() :
         \ '' != expand('%:t') ? expand('%:t') : '[No Name]') .
         \ ('' != LightLineModified() ? ' ' . LightLineModified() : '')
  endfunction

  function! LightLineFugitive()
    if &ft !~? 'vimfiler\|gundo' && exists("*fugitive#head")
      let branch = fugitive#head()
      return branch !=# '' ? "\ue0a0 ".branch : ''
    endif
    return ''
  endfunction

  function! LightLineFileformat()
    return winwidth(0) > 70 ? &fileformat : ''
  endfunction

  function! LightLineFiletype()
    return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
  endfunction

  function! LightLineFileencoding()
    return winwidth(0) > 70 ? (&fenc !=# '' ? &fenc : &enc) : ''
  endfunction

  function! LightLineMode()
    return winwidth(0) > 60 ? lightline#mode() : ''
  endfunction
'''

# Completion {{{1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['context_filetype.vim']
build = 'pip3 install neovim'
on_i = 1
hook_add = '''
  " Use deoplete.
  let g:deoplete#enable_at_startup = 1
  " Use smartcase.
  let g:deoplete#enable_smart_case = 1
  " Set minimum syntax keyword length.
  let g:deoplete#auto_complete_start_length = 2
  " <CR>: close popup and save indent.
  inoremap <silent><CR> <C-r>=<SID>my_cr_function()<CR>
  function! s:my_cr_function() abort
    return deoplete#close_popup() . "\<CR>"
  endfunction
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_ft = 'snippet'
hook_add = '''
  " Plugin key-mappings.
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  " Enable snipMate compatibility feature.
  let g:neosnippet#enable_snipmate_compatibility = 1
  " Expand the function prototype.
  let g:neosnippet#enable_completed_snippet = 1
  " Expand snippets by a word boundary.
  let g:neosnippet#expand_word_boundary = 1
  " SuperTab like snippets behavior.
  imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
     \ "\<Plug>(neosnippet_expand_or_jump)" :
     \ pumvisible() ? "\<C-n>" : "\<TAB>"
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
     \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
  " For conceal markers.
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = 'neosnippet.vim'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# TextObject {{{1

[[plugins]]
repo = 'bkad/CamelCaseMotion'
on_map = '<Plug>CamelCaseMotion_'
hook_add = '''
  " Plugin key-mappings.
  map <silent>w  <Plug>CamelCaseMotion_w
  map <silent>b  <Plug>CamelCaseMotion_b
  map <silent>e  <Plug>CamelCaseMotion_e
  map <silent>ge <Plug>CamelCaseMotion_ge
  sunmap w
  sunmap b
  sunmap e
  sunmap ge
  omap <silent>iw <Plug>CamelCaseMotion_iw
  xmap <silent>iw <Plug>CamelCaseMotion_iw
  omap <silent>ib <Plug>CamelCaseMotion_ib
  xmap <silent>ib <Plug>CamelCaseMotion_ib
  omap <silent>ie <Plug>CamelCaseMotion_ie
  xmap <silent>ie <Plug>CamelCaseMotion_ie
'''

[[plugins]]
repo = 'vim-scripts/matchit.zip'
on_map = '%'

[[plugins]]
repo = 'AndrewRadev/switch.vim'
on_map = '-'
hook_add = '''
  " Plugin key-mappings.
  let g:switch_mapping = '-'
'''

[[plugins]]
repo = 'kana/vim-operator-user'
on_source = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = ['vim-operator-user']
on_map = '<Plug>'
hook_add = '''
  " Plugin key-mappings.
  omap <silent>s <Plug>(operator-surround-append)
  xmap <silent>s <Plug>(operator-surround-append)
  map <silent>ds <Plug>(operator-surround-delete)a
  map <silent>cs <Plug>(operator-surround-replace)a
'''

# Util {{{1

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_map = '<Plug>'
hook_add = '''
  " Plugin key-mappings.
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star-with-echo)
  nmap # <Plug>(anzu-sharp-with-echo)
  nmap <Esc><Esc> <Plug>(anzu-clear-search-status)
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_map = ['gc', 'g<', 'g>']

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = '<Plug>(EasyAlign)'
hook_add = '''
  " Plugin key-mappings.
  xmap <silent><Enter> <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'sjl/gundo.vim'
build = 'pip install neovim'
on_cmd = 'Gundo'
hook_add = '''
  " Plugin key-mappings.
  nnoremap <silent><Space>U :<C-u>GundoToggle<CR>
'''

# File {{{1

[[plugins]]
repo = 'Shougo/deol.nvim'
on_map = '<Plug>'
hook_add = '''
  " The prefix key.
  nnoremap [deol]   <Nop>
  nmap     <Space>s [deol]
  " Plugin key-mappings.
  nnoremap <silent>[deol]n :<C-u>call deol#new({ 'command': 'zsh' })<CR><CR>
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
on_map = '<Plug>'
hook_add = '''
  " The prefix key.
  nnoremap [filer]  <Nop>
  nmap     <Space>f [filer]
  " Plugin key-mappings.
  nnoremap <silent>[filer]n :<C-u>VimFilerBufferDir<CR>
  nnoremap <silent>[filer]c :<C-u>VimFilerCurrentDir<CR>
  " Use vimfiler as default explorer.
  let g:vimfiler_as_default_explorer = 1
  " Enable file operation commands.
  let g:vimfiler_safe_mode_by_default = 0
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim', 'vim-denite-ghq', 'unite.vim']
on_cmd = 'Denite'
hook_add = '''
  " The prefix key.
  nnoremap [denite] <Nop>
  nmap     <Space>u [denite]
  " Plugin key-mappings.
  nnoremap <silent>[denite]f :<C-u>Denite file_rec -default-action=tabswitch -direction=top<CR>
  nnoremap <silent>[denite]g :<C-u>Denite grep -auto-preview -default-action=tabswitch -direction=top -vertical-preview<CR>
  nnoremap <silent>[denite]b :<C-u>Denite buffer -default-action=tabswitch -direction=top<CR>
  nnoremap <silent>[denite]r :<C-u>Denite register -direction=top<CR>
  nnoremap <silent>[denite]o :<C-u>Denite outline -direction=top<CR>
  nnoremap <silent>[denite]H :<C-u>Denite help -direction=top<CR>
'''
hook_source = '''
  " " Plugin key-mappings.
  " call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
  " call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')
  " Use pt in denite sources.
  if executable('pt')
    call denite#custom#var('file_rec', 'command',
          \ ['pt', '--follow', '--nocolor', '--nogroup', '-g', ''])
    call denite#custom#var('grep', 'command', ['pt'])
    call denite#custom#var('grep', 'default_opts',
          \ ['--nogroup', '--nocolor', '--smart-case'])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', [])
    call denite#custom#var('grep', 'separator', ['--'])
    call denite#custom#var('grep', 'final_opts', [])
  endif
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'
hook_add = '''
  " Plugin key-mappings.
  nnoremap <silent>[denite]mf :<C-u>Denite file_mru -default-action=tabswitch -direction=top<CR>
'''

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'
hook_add = '''
  " Plugin key-mappings.
  nnoremap <silent>[denite]s :<C-u>Denite ghq -direction=top<CR>
'''

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['vim-ref-ri', 'unite-rails', 'unite-codic.vim']
on_source = 'denite.nvim'

# Runner {{{1

[[plugins]]
repo = 'neomake/neomake'
on_event = 'BufWritePost'
hook_add = '''
  " Runs Neomake on the current file on every write.
  autocmd MyAutoCmd BufWritePost * Neomake
  " Sign settings.
  let g:neomake_error_sign   = { 'text': '>>', 'texthl': 'ErrorMsg' }
  let g:neomake_warning_sign = { 'text': '>>', 'texthl': 'Todo' }
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'

[[plugins]]
repo = 'vim-scripts/sudo.vim'
on_cmd = ['SudoRead', 'SudoWrite']

[[plugins]]
repo = 'janko-m/vim-test'
hook_add = '''
  " Plugin key-mappings.
  nnoremap <silent><Leader>c :<C-u>TestFile<CR>
  nnoremap <silent><Leader>n :<C-u>TestNearest<CR>
  nnoremap <silent><Leader>l :<C-u>TestLast<CR>
  nnoremap <silent><Leader>a :<C-u>TestSuite<CR>
  " Runs test commands with `:Dispatch`.
  let test#strategy = 'dispatch'
'''

[[plugins]]
repo = 'tpope/vim-dispatch'

# Git {{{1

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
  " The prefix key.
  nnoremap [git]    <Nop>
  nmap     <Space>g [git]
  " Plugin key-mappings.
  nnoremap <silent>[git]s :<C-u>Gina status<CR>
  nnoremap <silent>[git]c :<C-u>Gina commit<CR>
  nnoremap <silent>[git]B :<C-u>Gina branch -a<CR>
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  " Plugin key-mappings.
  nnoremap <silent>[git]d :<C-u>Gdiff<CR>
  nnoremap <silent>[git]a :<C-u>Gwrite<CR>
  nnoremap <silent>[git]r :<C-u>Gread<CR>
  nnoremap <silent>[git]b :<C-u>Gblame<CR>
'''

[[plugins]]
repo = 'cohama/agit.vim'
hook_add = '''
  " Plugin key-mappings.
  nnoremap <silent>[git]l :<C-u>Agit<CR>
  nnoremap <silent>[git]f :<C-u>AgitFile<CR>
  autocmd FileType agit call s:my_agit_setting()
  function! s:my_agit_setting()
    nmap <buffer>cp <Plug>(agit-git-cherry-pick)
    nmap <buffer>rv <Plug>(agit-git-revert)
  endfunction
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

# FileType {{{1

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_source = 'vim-precious'

[[plugins]]
repo = 'thinca/vim-ref'
depends = ['vim-ref-ri']

# Ruby {{{2
[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = 'ruby'

[[plugins]]
repo = 'yuku-t/vim-ref-ri'
on_source = ['vim-ref', 'unite.vim']
hook_add = '''
  " Plugin key-mappings.
  nnoremap <silent>[denite]R :<C-u>Denite unite:ref/ri<CR>
'''

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'basyura/unite-rails'
on_ft = 'ruby'
on_source = 'unite.vim'
hook_add = '''
  " The prefix key.
  nnoremap [rails]  <Nop>
  nmap     <Space>r [rails]
  " Plugin key-mappings.
  nnoremap <silent>[rails]m :<C-u>Denite unite:rails/model<CR>
  nnoremap <silent>[rails]v :<C-u>Denite unite:rails/view<CR>
  nnoremap <silent>[rails]c :<C-u>Denite unite:rails/controller<CR>
  nnoremap <silent>[rails]h :<C-u>Denite unite:rails/helper<CR>
  nnoremap <silent>[rails]s :<C-u>Denite unite:rails/spec<CR>
  nnoremap <silent>[rails]C :<C-u>Denite unite:rails/config<CR>
  nnoremap <silent>[rails]l :<C-u>Denite unite:rails/log<CR>
'''

[[plugins]]
repo = 'Keithbsmiley/rspec.vim'
on_ft = 'ruby'

# Go {{{2
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

# HTML {{{2
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

# JavaScript {{{2
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'
on_ft = 'javascript'
hook_add = '''
  " Use brief mode.
  let g:SimpleJsIndenter_BriefMode = 1
  " The some more smart case indent.
  let g:SimpleJsIndenter_CaseIndentLevel = -1
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

# Markdown {{{2
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  augroup MarkdownSettings
    autocmd!
    " Set markdown indent style.
    autocmd FileType markdown set tabstop=4 shiftwidth=4
    " Disable AutoRemoveTrailingSpaces.
    autocmd FileType markdown autocmd! AutoRemoveTrailingSpaces
  augroup END
'''

[[plugins]]
repo = 'kannokanno/previm'
depends = ['open-browser.vim']
on_cmd = 'PrevimOpen'
hook_add = '''
  " Plugin key-mappings.
  nnoremap <silent><Leader>p :<C-u>PrevimOpen<CR>
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

# English {{{2
[[plugins]]
repo = 'ujihisa/neco-look'
on_source = 'deoplete.nvim'

[[plugins]]
repo = 'koron/codic-vim'
depends = ['unite-codic.vim']

[[plugins]]
repo = 'rhysd/unite-codic.vim'
on_source = 'codic-vim'
hook_add = '''
  " Plugin key-mappings.
  nnoremap <silent>[denite]C :<C-u>Denite unite:codic<CR>
'''

# Others {{{2
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = 'yaml'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'darfink/vim-plist'

[[plugins]]
repo = 'rhysd/github-complete.vim'
hook_add = '''
  " Use neocomplete.
  let g:github_complete_enable_neocomplete = 1
'''

[[plugins]]
repo = 'kakkyz81/evervim'
build = 'pip install markdown'
hook_add = '''
  " Set Evernote developer token.
  let g:evervim_devtoken = ''
  " The prefix key.
  nnoremap [evervim] <Nop>
  nmap     <Space>e  [evervim]
  " Plugin key-mappings.
  nnoremap <silent>[evervim]l :<C-u>EvervimNotebookList<CR>
  nnoremap <silent>[evervim]c :<C-u>EvervimCreateNote<CR>
  nnoremap         [evervim]s :<C-u>EvervimSearchByQuery<Space>
  " Set the work path.
  let g:evervim_workdir = expand('~/.cache/evervim')
'''

# Folding {{{1

# vim:set foldmethod=marker:
