
# tap repositories and their packages

tap homebrew/core
brew awscli
brew fd
brew fzf
brew ghq
brew git
brew git-flow-avh
brew git-secrets
brew go
brew graphviz
brew hub --devel
brew imagemagick
brew mackup
brew mas
brew neovim
brew node-build
brew nodenv
brew packer
brew postgresql
brew python
brew python3
brew rbenv
brew rbenv-default-gems
brew reattach-to-user-namespace
brew redis
brew ripgrep
brew ruby-build
brew shellcheck
brew sqlite
brew terraform
brew tmux
brew yarn --without-node
brew zplug
brew zsh

tap caskroom/cask
cask slack
cask flume
cask cheatsheet
cask skype
cask appcleaner
cask karabiner-elements
cask lacaille
cask zoomus
cask keepingyouawake
cask avira-antivirus
cask iterm2
cask dropbox
cask insomnia
cask chatwork
cask hosts
cask cooviewer
cask docker
cask kindle
cask adobe-creative-cloud
cask clipy
cask lastfm
cask duet
cask night-owl
cask iina
cask microsoft-office
cask vox
cask google-chrome
cask postico
cask google-japanese-ime
cask bettertouchtool
cask skitch
cask rubymotion
cask zeplin
cask openemu

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty --with-powerline

# App Store applications
appstore 443987910 1Password (6.8.4)
appstore 412448059 ForkLift (2.6.6)
appstore 409183694 Keynote (7.3.1)
appstore 539883307 LINE (5.4.2)
appstore 1289197285 MindNode (5.0.1)
appstore 568494494 Pocket (1.6.6)
appstore 413449473 ReceiptKeeper (1.1.3)
appstore 880001334 Reeder (3.1.2)
appstore 585829637 Todoist (7.0.6)
