
# tap repositories and their packages

tap homebrew/core
brew awscli
brew fd
brew fzf
brew ghq
brew git
brew git-flow-avh
brew git-secrets
brew go
brew graphviz
brew hub
brew imagemagick@6
brew mackup
brew mas
brew mitmproxy
brew neovim
brew node-build
brew nodenv
brew packer
brew postgresql
brew python
brew rbenv
brew rbenv-default-gems
brew reattach-to-user-namespace
brew redis
brew ripgrep
brew ruby-build
brew shellcheck
brew sqlite
brew ssh-copy-id
brew terraform
brew tmux
brew yarn --without-node
brew zplug
brew zsh

tap caskroom/cask

tap mscharley/homebrew
brew alacritty

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty --with-powerline

# Other Homebrew packages
brew python3

# Other Cask applications
cask adobe-creative-cloud
cask appcleaner
cask avira-antivirus
cask bettertouchtool
cask chatwork
cask cheatsheet
cask clipy
cask cooviewer
cask docker
cask dropbox
cask duet
cask flume
cask google-chrome
cask google-japanese-ime
cask hosts
cask iina
cask insomnia
cask karabiner-elements
cask keepingyouawake
cask kindle
cask lacaille
cask lastfm
cask microsoft-office
cask night-owl
cask openemu
cask postico
cask rubymotion
cask skitch
cask skype
cask slack
cask vox
cask zeplin
cask zoomus

# App Store applications
appstore 443987910 1Password (6.8.4)
appstore 412448059 ForkLift (2.6.6)
appstore 409183694 Keynote (7.3.1)
appstore 539883307 LINE (5.4.2)
appstore 1289197285 MindNode (5.0.1)
appstore 568494494 Pocket (1.6.6)
appstore 413449473 ReceiptKeeper (1.1.3)
appstore 880001334 Reeder (3.1.2)
appstore 585829637 Todoist (7.0.6)
