
# tap repositories and their packages

tap homebrew/core
brew awscli
brew elm
brew elm-format
brew exa
brew fd
brew fzf
brew ghq
brew git
brew git-crypt
brew git-flow-avh
brew git-secrets
brew gitmoji
brew gnupg
brew go
brew graphviz
brew hadolint
brew hub
brew imagemagick
brew jq
brew jsonlint --ignore-dependencies
brew mackup
brew mas
brew mcrypt
brew mitmproxy
brew neovim
brew node-build
brew nodenv
brew nushell
brew rbenv
brew rbenv-binstubs --HEAD
brew rbenv-default-gems
brew readline
brew reattach-to-user-namespace
brew ripgrep
brew ruby-build
brew shellcheck
brew sqlite
brew ssh-copy-id
brew starship
brew tfenv
brew tmux
brew yamllint
brew yarn --ignore-dependencies
brew zplug
brew zsh

tap homebrew/cask-drivers
cask silicon-labs-vcp-driver
cask sonos

tap homebrew/services

tap homebrew/cask
cask adobe-creative-cloud
cask alacritty
cask amazon-music
cask appcleaner
cask avira-antivirus
cask bettertouchtool
cask camera-live
cask clipy
cask deepl
cask docker
cask drawio
cask dropbox
cask flume
cask forklift
cask google-chrome
cask google-japanese-ime
cask iina
cask insomnia
cask karabiner-elements
cask keepingyouawake
cask kindle
cask microsoft-office
cask ngrok
cask night-owl
cask notion
cask obs
cask obs-virtualcam
cask openemu
cask quip
cask rubymotion
cask skype
cask station
cask stoplight-studio
cask tableplus
cask unshaky
cask vox
cask zeplin
cask zoomus

tap kwilczynski/pkenv
brew pkenv

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask font-cica
cask miro-formerly-realtimeboard

# App Store applications
appstore 1333542190 1Password 7 (7.6)
appstore 571213070 DaVinci Resolve (16.2.5)
appstore 1206246482 EdgeView 2 (2.842)
appstore 409183694 Keynote (10.1)
appstore 539883307 LINE (6.2.2)
appstore 1289197285 MindNode (7.3.2)
appstore 568494494 Pocket (1.8.5)
appstore 413449473 ReceiptKeeper (1.1.3)
appstore 880001334 Reeder (3.2.3)
appstore 585829637 Todoist (7.3.2)
